### ISSUE TITLE
error: package AdRequest does not exist

### ISSUE THREAD

**Issue by B3L7** [admob-plus/admob-plus#41]
### Is this a bug report?
Yes

### Environment

AdMob Plus Environment Info:
    System:
      OS: Linux 4.19 Arch Linux undefined
      CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
      Memory: 772.13 MB / 7.67 GB
      Shell: 4.4.23 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2
    npmGlobalPackages:
      cordova: 8.1.2

### Steps to Reproduce

(Write your steps here:)

1. Update to 0.12.0
2. Run Cordova Build Android
3. Build Fails: error: package AdRequest does not exist
    protected AdRequest.Builder createAdRequestBuilder() {

### Expected Behavior

Expected successful build. v0.11 built without issues.

### Actual Behavior

BUILD FAILED in 5s
26 actionable tasks: 6 executed, 20 up-to-date
/home/b3l7/Repos/eternityPilot/platforms/android/gradlew: Command failed with exit code 1 Error output:
/home/b3l7/Repos/eternityPilot/platforms/android/app/src/main/java/admob/plugin/AbstractExecutor.java:14: error: package AdRequest does not exist
    protected AdRequest.Builder createAdRequestBuilder() {
                       ^
/home/b3l7/Repos/eternityPilot/platforms/android/app/src/main/java/admob/plugin/AbstractExecutor.java:15: error: package AdRequest does not exist
        return new AdRequest.Builder();
                            ^

### Reproducible Demo

I'd be willing to give the admob-plus author access to my private bitbucket repo but I do not want to make my app public at this time.

**Comment by svzi** [comment]
@ratson I'm having the same problem, since updating from `admob-plus` 0.6.0 to 0.12.1.

Here is my system info (from your cli tool):
```
  AdMob Plus Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 1.23 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      cc.fovea.cordova.purchase: ^7.1.3 => 7.1.3 
      cordova-admob-plus: ^0.12.1 => 0.12.1 
      cordova-android: 7.0.0 => 7.0.0 
      cordova-clipboard: 1.2.1 => 1.2.1 
      cordova-ios: 4.5.5 => 4.5.5 
      cordova-ios-plugin-no-export-compliance: 0.0.5 => 0.0.5 
      cordova-plugin-app-version: ^0.1.9 => 0.1.9 
      cordova-plugin-appavailability: ^0.4.2 => 0.4.2 
      cordova-plugin-apprate: ^1.4.0 => 1.4.0 
      cordova-plugin-browsertab: ^0.2.0 => 0.2.0 
      cordova-plugin-device: ^2.0.2 => 2.0.2 
      cordova-plugin-dialogs: ^2.0.1 => 2.0.1 
      cordova-plugin-email-composer: ^0.8.15 => 0.8.15 
      cordova-plugin-file: ^6.0.1 => 6.0.1 
      cordova-plugin-firebase: ^2.0.5 => 2.0.5 
      cordova-plugin-globalization: ^1.11.0 => 1.11.0 
      cordova-plugin-inappbrowser: ^3.0.0 => 3.0.0 
      cordova-plugin-ionic: ^5.1.2 => 5.1.2 
      cordova-plugin-ionic-keyboard: ^2.1.2 => 2.1.2 
      cordova-plugin-ionic-webview: ^2.2.0 => 2.2.0 
      cordova-plugin-network-information: 2.0.1 => 2.0.1 
      cordova-plugin-splashscreen: ^5.0.2 => 5.0.2 
      cordova-plugin-statusbar: ^2.4.2 => 2.4.2 
      cordova-plugin-whitelist: ^1.3.3 => 1.3.3 
      cordova-plugin-x-socialsharing: ^5.4.1 => 5.4.1 
    npmGlobalPackages:
      cordova: 8.1.2
      ionic: 4.3.1

AndroidManifest.xml: looks ok
```
Part of the build log from my Ionic 3 app:
```
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
/Users/svzi/development/_own/xxx/app/platforms/android/app/src/main/java/admob/plugin/AbstractExecutor.java:14: error: package AdRequest does not exist
    protected AdRequest.Builder createAdRequestBuilder() {
                       ^
/Users/svzi/development/_own/xxx/app/platforms/android/app/src/main/java/admob/plugin/AbstractExecutor.java:15: error: package AdRequest does not exist
        return new AdRequest.Builder();
                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/svzi/development/_own/xxx/app/platforms/android/app/src/main/java/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

I've also tried with version 0.12.0, but the issue remains. I've dropped my platform, removed my node_modules folder and everything I could think of, but nothing helped.

Any idea what's going wrong here?

**Comment by svzi** [comment]
Android build is working fine again with version 0.13.0! Thanks for the quick fix!
