### ISSUE TITLE
[iOS] Can't build app with versions 0.12+

### ISSUE THREAD

**Issue by svzi** [admob-plus/admob-plus#42]
### Is this a bug report?

Yes.

### Environment

I've upgraded yesterday your plugin from version 0.6.0 to 0.12.1 and today 0.13.0. With the old version I could build without an issue.

```
 ~> npx admob-plus info --clipboard
npx: Installierte 92 in 8.435s

  AdMob Plus Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 705.91 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    Languages:
      Java: 1.8.0 - /usr/bin/javac
    npmPackages:
      cc.fovea.cordova.purchase: ^7.1.3 => 7.1.3
      cordova-admob-plus: ^0.13.0 => 0.13.0
      cordova-android: 7.0.0 => 7.0.0
      cordova-clipboard: 1.2.1 => 1.2.1
      cordova-ios: 4.5.5 => 4.5.5
      cordova-ios-plugin-no-export-compliance: 0.0.5 => 0.0.5
      cordova-plugin-app-version: ^0.1.9 => 0.1.9
      cordova-plugin-appavailability: ^0.4.2 => 0.4.2
      cordova-plugin-apprate: ^1.4.0 => 1.4.0
      cordova-plugin-browsertab: ^0.2.0 => 0.2.0
      cordova-plugin-device: ^2.0.2 => 2.0.2
      cordova-plugin-dialogs: ^2.0.1 => 2.0.1
      cordova-plugin-email-composer: ^0.8.15 => 0.8.15
      cordova-plugin-file: ^6.0.1 => 6.0.1
      cordova-plugin-firebase: ^2.0.5 => 2.0.5
      cordova-plugin-globalization: ^1.11.0 => 1.11.0
      cordova-plugin-inappbrowser: ^3.0.0 => 3.0.0
      cordova-plugin-ionic: ^5.1.2 => 5.1.2
      cordova-plugin-ionic-keyboard: ^2.1.2 => 2.1.2
      cordova-plugin-ionic-webview: ^2.2.0 => 2.2.0
      cordova-plugin-network-information: 2.0.1 => 2.0.1
      cordova-plugin-splashscreen: ^5.0.2 => 5.0.2
      cordova-plugin-statusbar: ^2.4.2 => 2.4.2
      cordova-plugin-whitelist: ^1.3.3 => 1.3.3
      cordova-plugin-x-socialsharing: ^5.4.1 => 5.4.1
    npmGlobalPackages:
      cordova: 8.1.2
      ionic: 4.3.1

AndroidManifest.xml: looks ok
```

### Steps to Reproduce

1. Add plugin to Ionic3 app.
2. Try to build iOS app via command line (`ionic cordova build ios`)

### Actual Behavior

I see the following logs:
```
...
/Users/svzi/development/_own/xxx/app/platforms/ios/xxx/Bridging-Header.h:29:9: note: in file included from /Users/svzi/development/_own/xxx/app/platforms/ios/xxx/Bridging-Header.h:29:
#import "AMSPlugin-Bridging-Header.h"
        ^
/Users/svzi/development/_own/xxx/app/platforms/ios/xxx/Plugins/cordova-admob-plus/AMSPlugin-Bridging-Header.h:2:9: error: 'GoogleMobileAds/GoogleMobileAds.h' file not found
#import <GoogleMobileAds/GoogleMobileAds.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/svzi/development/_own/xxx/app/platforms/ios/build/sharedpch/Bridging-Header-swift_2UY9OHTLVOSLN-clang_2H1QBL2F1GQ6C.pch' for bridging header '/Users/svzi/development/_own/xxx/app/platforms/ios/xxx/Bridging-Header.h'

** ARCHIVE FAILED **
```

### Reproducible Demo

This shouldn't be hard to track down, but if you really need a demo, I will provide one. Just let me know.

**Comment by ratson** [comment]
I can not tell anything from the error, it would be helpful to have a demo for the problem.

**Comment by svzi** [comment]
I've updated your plugin again, I'm now using version 0.15.0 and at the first look it seemed that the issue still exists. But I noticed that I didn't update your `ionic-admob` package. I was still using version 0.6.0! After updating that package to 0.15.0, I was able build for iOS again!
