### ISSUE TITLE
Not working with FAN 5.4

### ISSUE THREAD

**Issue by llapps** [admob-plus/admob-plus#113]
Hi,
thank yo for your work!

I tried to use your plugin together wth cordova-plugin-admob-mediation to use facebook mediation. But no ads are displayed, I used a clean test app with that two plugins and play service 17.2.1 but only ads from admob are shown. even when they are last in mediation.

maybe this can help?
08-01 18:18:21.600 I/zygote64(15260): Rejecting re-init on previously-failed class java.lang.Class<com.google.ads.mediation.facebook.FacebookMediationAdapter>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/mediation/rtb/RtbAdapter;

08-01 18:18:21.600 I/zygote64(15260): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.mediation.rtb.RtbAdapter" on path: DexPathList[[zip file "/data/app/XXXXXXXXXXXXXXXXXX-fEwOLmjLFvmPKz6b3xrQTQ==/base.apk"],nativeLibraryDirectories=[/data/app/dating.app.chat.flirt.wgbcv-fEwOLmjLFvmPKz6b3xrQTQ==/lib/arm64, /system/lib64, /vendor/lib64]]

Any suggestions?

Regards,
Oliver
